# Generated by Django 3.1.2 on 2020-11-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('id_producto', models.CharField(max_length=200)),
                ('cantidad_producto', models.SmallIntegerField()),
                ('total_producto', models.IntegerField()),
            ],
            options={
                'ordering': ('-id_carrito', '-id_producto'),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Nombre1', models.CharField(max_length=50)),
                ('Nombre2', models.CharField(max_length=50)),
                ('Apellido1', models.CharField(max_length=50)),
                ('Apellido2', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-Nombre1', '-Apellido1'),
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('numero_cuenta', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('valor_total', models.IntegerField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.carrito')),
            ],
            options={
                'ordering': ('-numero_cuenta', '-valor_total'),
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cliente'),
        ),
    ]
