# Generated by Django 3.1.2 on 2020-11-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='admin_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria_producto',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
