# Generated by Django 3.1.2 on 2020-11-28 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201127_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('-primer_nombre', '-primer_apellido')},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='id_cliente',
            new_name='cédula',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='dirección',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido1',
            new_name='primer_apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido2',
            new_name='primer_nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre1',
            new_name='segundo_apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre2',
            new_name='segundo_nombre',
        ),
    ]
