# Generated by Django 3.1.3 on 2020-12-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201127_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='id_carrito',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='id_domiciliario',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='numero_cuenta',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Domiciliario',
        ),
        migrations.DeleteModel(
            name='Domicilio',
        ),
    ]
