# Generated by Django 3.1.2 on 2020-11-07 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('cedula_admin', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Nombre1', models.CharField(max_length=50)),
                ('Nombre2', models.CharField(max_length=50)),
                ('Apellido1', models.CharField(max_length=50)),
                ('Apellido2', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-cedula_admin',),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-especie',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio_producto', models.IntegerField()),
                ('precio_produccion', models.IntegerField()),
                ('admin_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.admin')),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoria')),
            ],
            options={
                'ordering': ('-precio_producto', '-nombre_producto'),
            },
        ),
    ]
