# Generated by Django 3.1.3 on 2020-11-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Nombre1', models.CharField(max_length=50)),
                ('Nombre2', models.CharField(max_length=50)),
                ('Apellido1', models.CharField(max_length=50)),
                ('Apellido2', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-Nombre1', '-Apellido1'),
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.CharField(max_length=200)),
                ('id_producto', models.CharField(max_length=200)),
                ('cantidad_producto', models.SmallIntegerField()),
                ('total_producto', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cliente')),
            ],
            options={
                'ordering': ('-id_carrito', '-id_producto'),
                'unique_together': {('id_carrito', 'id_producto')},
            },
        ),
    ]
