# Generated by Django 3.1.2 on 2020-11-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('id_producto', models.CharField(max_length=200)),
                ('cantidad_producto', models.SmallIntegerField()),
                ('total_producto', models.IntegerField()),
            ],
            options={
                'ordering': ('-id_carrito', '-id_producto'),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-nombre1', '-apellido1'),
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('numero_cuenta', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('valor_total', models.IntegerField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.carrito')),
            ],
            options={
                'ordering': ('-numero_cuenta', '-valor_total'),
            },
        ),
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('id_domiciliario', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('medio_transporte', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-id_domiciliario', '-medio_transporte'),
            },
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Apellido1',
            new_name='apellido1',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Apellido2',
            new_name='apellido2',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Nombre1',
            new_name='nombre1',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Nombre2',
            new_name='nombre2',
        ),
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('metodo_de_pago', models.CharField(max_length=50)),
                ('id_domiciliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.domiciliario')),
                ('numero_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cuenta')),
            ],
            options={
                'ordering': ('-id_domicilio', '-id_domiciliario'),
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cliente'),
        ),
    ]
