# Generated by Django 3.1.2 on 2020-11-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201107_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('id_domicilario', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Nombre1', models.CharField(max_length=50)),
                ('Nombre2', models.CharField(max_length=50)),
                ('Apellido1', models.CharField(max_length=50)),
                ('Apellido2', models.CharField(max_length=50)),
                ('Medio_transporte', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-id_domicilario', '-Medio_transporte'),
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('metodo_de_pago', models.CharField(max_length=50)),
                ('id_domiciliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.domiciliario')),
                ('numero_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cuenta')),
            ],
            options={
                'ordering': ('-id_domicilio', '-id_domiciliario'),
            },
        ),
    ]
