# Generated by Django 3.1 on 2020-11-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_domiciliario_domicilio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('-nombre1', '-apellido1')},
        ),
        migrations.AlterModelOptions(
            name='domiciliario',
            options={'ordering': ('-id_domiciliario', '-medio_transporte')},
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Apellido1',
            new_name='apellido1',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Apellido2',
            new_name='apellido2',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Nombre1',
            new_name='nombre1',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Nombre2',
            new_name='nombre2',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Apellido1',
            new_name='apellido1',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Apellido2',
            new_name='apellido2',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nombre1',
            new_name='nombre1',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nombre2',
            new_name='nombre2',
        ),
        migrations.RenameField(
            model_name='domiciliario',
            old_name='Apellido1',
            new_name='apellido1',
        ),
        migrations.RenameField(
            model_name='domiciliario',
            old_name='Apellido2',
            new_name='apellido2',
        ),
        migrations.RenameField(
            model_name='domiciliario',
            old_name='id_domicilario',
            new_name='id_domiciliario',
        ),
        migrations.RenameField(
            model_name='domiciliario',
            old_name='Medio_transporte',
            new_name='medio_transporte',
        ),
        migrations.RenameField(
            model_name='domiciliario',
            old_name='Nombre1',
            new_name='nombre1',
        ),
        migrations.RenameField(
            model_name='domiciliario',
            old_name='Nombre2',
            new_name='nombre2',
        ),
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
