# Generated by Django 3.1.3 on 2020-11-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201107_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
