# Generated by Django 3.1.3 on 2020-11-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_producto_especificaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domiciliario',
            options={'ordering': ('-id_domiciliario', '-medio_transporte')},
        ),
        migrations.RenameField(
            model_name='domiciliario',
            old_name='id_domicilario',
            new_name='id_domiciliario',
        ),
    ]
