# Generated by Django 3.1.3 on 2020-12-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='id_cliente',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cédula',
            new_name='cedula',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
