# Generated by Django 3.1.3 on 2020-12-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0002_auto_20201201_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-especie',),
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='etiqueta',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carrito_compra.categoria'),
            preserve_default=False,
        ),
    ]
