# Generated by Django 3.1.3 on 2020-12-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0003_auto_20201201_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='product'),
            preserve_default=False,
        ),
    ]
