# Generated by Django 3.1.3 on 2020-12-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0004_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_descuento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
