# Generated by Django 3.1.3 on 2020-12-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0005_producto_precio_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(default='Un muy buen producto'),
            preserve_default=False,
        ),
    ]
