# Generated by Django 3.1.3 on 2020-12-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0006_producto_especificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
