# Generated by Django 3.1.3 on 2020-12-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0007_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='productocarrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
