# Generated by Django 3.1.3 on 2020-12-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0008_auto_20201201_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocarrito',
            name='orden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productocarrito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito_compra.cliente'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito_compra.cliente'),
        ),
    ]
