# Generated by Django 3.1.3 on 2020-12-01 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0009_auto_20201201_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito_compra.cliente'),
        ),
        migrations.AlterField(
            model_name='productocarrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito_compra.cliente'),
        ),
    ]
