# Generated by Django 3.1.3 on 2020-12-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0010_auto_20201201_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocarrito',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='productocarrito',
            name='usuario',
        ),
    ]
