# Generated by Django 3.1.3 on 2020-12-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0014_auto_20201203_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
